### ISSUE TITLE
RPJ Lavender and other Filter - Polyphonic Bug

### ISSUE THREAD

**Issue by mosesve** [kockie69/RPJ#45]
Hi Robert,

I just came across a strange bug in your filters. 

![image](https://user-images.githubusercontent.com/78504632/150599950-f4e265f4-f501-42cd-b997-cc4c598e0668.png)

When using a polyphonic envelope for cutoff, the wrong channels are triggered. After a while it stops to open the filter at all and outputs fast rising or falling voltages, even when disconnect the polyphonyc envelope and just use a trigger to open the filter.

**Comment by kockie69** [comment]
Interesting, looks to me more is wrong with it not only in poly mode. Nice one for the weekend whilst waiting the other versions come live....

**Comment by kockie69** [comment]
This one should fix the rising and falling. It was caused by the Fc being able to get to 0. This filter will move to endless if that happens.

https://github.com/kockie69/RPJ/actions/runs/1733477380

**Comment by mosesve** [comment]
That fixed the rising and falling.

**Comment by kockie69** [comment]
The Cutoff isn't poly at the moment. I am looking at the moment how to improve these filters. Add drive, and I want to add more controls to them.  Also make the Fc poly and make them stereo.

**Comment by squinkylabs** [comment]
F2 filter is similar, and I think Fc is poly.

**Comment by kockie69** [comment]
This should be solved in the next release. Latest build version to test available from here:

https://github.com/kockie69/RPJ/actions

**Comment by squinkylabs** [comment]
F2 intentionally has no drive. It's can't distort. To make it distort and not alias "something" would need to be done. In Stairway I used oversampling, since that's all I know that works for filters, although there are other ways.

In any case, F2 takes almost no CPU. Stairway is an utter pig. Although not only due to this.

It's in Interesting idea to make an F2 with distortion, but not sure how you would do it without killing the things it's good at.
